### ISSUE TITLE
Error in RTX mode

### ISSUE THREAD

**Issue by 010ender** [Null-MC/Shrimple#148]
Whenever I change the mode to RTX, up comes this error: 
`composite11.csh: composite11.csh: 0:360(30): error: variables of type sampler2D cannot be operands of the ?: operator
0:362(32): error: variables of type sampler2D cannot be operands of the ?: operator`
Other modes work perfectly fine.
**Version**: using v0.12, v0.9 is the last version that works for me; v.10 and v.11 produce artifacts and undesirable effects in RTX mode.
**GPU**: AMD RX 550
**CPU**: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
**OS**: Linux Mint 22.1
**Minecraft version**: Fabric 1.20.1 (many, many mods)

Additional info available upon request.

**Comment by florisvanderbamboe-crypto** [comment]
Yes, i also have the same problem. I whas using this shader on 1.21.4.
i have a 9060 xt 16gb gpu and ryzen 5 5600x cpu.
everything worked fine using fabric 1.21.4 on v0.12, except the rtx mode.
my OS is windows 11 pro.
and my error is the same i think: 
composite11.csh**
ERROR: 0:349: ':' : wrong operand types: no operation ':' exists that takes a left-hand operand of type 'uniform sampler2D' and a right operand of type 'uniform sampler2D'
ERROR: 0:349: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
also sorry if my english is bad.

**Comment by MiguVT** [comment]
Linux (cachyos, propietary nvidia drivers) same issue with RTX 3090
doesnt look like an amd-specific issue

terrain_translucent: terrain_translucent: 0(500) : error C1503: undefined variable "GetVoxelBlockPosition"
0(501) : error C1503: undefined variable "GetVoxelGridCell"
0(502) : error C1503: undefined variable "GetVoxelGridCellIndex"
0(503) : error C1503: undefined variable "IsTraceEmptyBlock"
0(503) : error C1503: undefined variable "SetVoxelBlockMask"
0(507) : error C1503: undefined variable "SetVoxelLightMask"
